### PR TITLE
Remove sprintf() calls in favor of using std::string

### PR DESCRIPTION
**Pull request by scotthunt**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by carrus85 — APPROVED** [review]
LGTM.

**Comment by scotthunt** [comment]
oops... this wasn't supposed to also have the v11b commits in it.  let me fix that.

EDIT: actually, since one of the changes is in the zstd command, maybe i'll leave it the way it is.  if we change the v11b commit in any way, i'll rebase this one

**Comment by carrus85** [comment]
Yeah; I'll just merge this and mark the other PR has handled here.

**Comment by carrus85** [comment]
Closes #27

**Pull request merged**
